[
  ./btop/btop.nix
  ./fastfetch/fastfetch.nix
  ./kitty/kitty.nix
  ./wms/hyprland.nix
  ./wms/waybar.nix
  ./git.nix
  ./rofi.nix
  ./zsh.nix
  ./wms/hyprpkgs.nix
  ./wms/swaync.nix
  ./wms/tofi.nix
  ./wms/hypridle.nix
  ./gtk.nix
]
